spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/student
    username: postgres
    password: 1928acchi
  jmx:
    default-domain: ex-emp
server:
  servlet:
    context-path: /ex-emp